name: 'queries'
version: '1.0.0'
config-version: 2

profile: 'queries'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


models:
  +persist_docs:
    relation: true
    columns: true
  queries:
    # Config indicated by + and applies to all files under models/example/
    infraestrutura_siscob_obras:
      +materialized: table # Materialization type (view, table or incremental)
      +schema: infraestrutura_siscob_obras # Overrides the default schema (defaults to what is set on profiles.yml)
    infraestrutura_siscob_obras_dashboard:
      +materialized: table # Materialization type (view, table or incremental)
      +schema: infraestrutura_siscob_obras_dashboard # Overrides the default schema (defaults to what is set on profiles.yml)
